data:
  split_regex: '.*_(.*)_'
  filter_regex: 'sag'
  # x, y, sequence length
  shape_y: 256
  shape_x: 256
  # files * slices <= sequence length, else the case is skipped
  sequence_length: 5
  q: 0.5
  # Quality preference
  normalize: 1961.06
  equal_images: True
  sequence_seed: 11
  multislice: False
  # data transformations
  undersampling: 8
  equal_masks: True
  mask_seed: 11
model:
  iterations: 5
  filters: 64
  kernelsize: 3
  channels: 1
  layers: 5

train:
  epochs: 75
  folds: 1
  loss:
    mse: 0
    ssim: 1
    dice: 0
  lr: 0.001
  lr_gamma: 0.95
  # 1 voor geen decay
  stop_lr_decay: 45
  # Stop na 45 epochs met LR decay, -1 voor nooit