data:
  batch_size: 10
  shape_y: 256
  shape_x: 256
  sequence_length: 5
  normalize: 1961.06
  undersampling: 8
  seed: 11

model:
  iterations: 2
  filters: 16
  kernelsize: 3
  channels: 1
  layers: 5

train:
  epochs: 3
  folds: 1
  loss:
    mse: 0
    ssim: 1
    dice: 0
  lr: 0.001
  lr_gamma: 0.95
  lr_decay_end: 45