data:
  split_regex: sag
  # x, y, sequence length
  shape: 256,256,15
  # files * slices <= sequence length, else the case is skipped
  slices: 3
train:
  epochs: 75
  folds: 1
  loss:
    mse: 1
    ssim: 0
    dice: 0
  lr: 0.001
  undersampling: 8
  seed: -1
experiment: