wandb_version: 1

in_dir:
  desc: null
  value: input\patient1
out_dir:
  desc: null
  value: output
debug:
  desc: null
  value: true
data:
  desc: null
  value:
    split_regex: .*_(.*)_
    filter_regex: sag
    shape_x: 256
    shape_y: 256
    sequence_length: 5
    sequence_seed: 11
    normalize: 1961.06
    undersampling: 8
    mask_seed: 11
model:
  desc: null
  value:
    iterations: 2
    filters: 16
    kernelsize: 3
    channels: 1
    layers: 5
    bcrnn: true
train:
  desc: null
  value:
    epochs: 3
    folds: 1
    loss:
      mse: 0.0
      ssim: 1.0
      dice: 0.0
    lr: 0.001
    lr_gamma: 0.95
    lr_decay_end: 45
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693391400.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.15.9
      8:
      - 3
      - 5
